-- select * from employees where department_id = 90;
-- select * from employees where salary > 5000;
-- select * from employees where last_name like "L%";
-- select * from departments where location_id = 1700;
-- select * from locations where country_id like "US";
-- select * from employees where first_name = "Lex" and last_name = "De Haan";
-- select * from employees where first_name = "Lex" or salary = 5800;